There were no error messages, however the output is missing 3 and 5 and could see the range was starting from 6 . 
hence corrected it . for i in range(1,max_num):and it worked .  
